// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Проверяет учётные данные и возвращает access-токен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход по email и паролю",
                "parameters": [
                    {
                        "description": "Email и пароль",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "невалидное тело",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "неверный email или пароль",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "JWT stateless: сервер токен не хранит — клиент удаляет access_token. Ответ 204 для единообразия с контрактом API.",
                "tags": [
                    "auth"
                ],
                "summary": "Выход",
                "responses": {
                    "204": {
                        "description": "нет тела"
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные пользователя по access-токену из заголовка Authorization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MeResponse"
                        }
                    },
                    "401": {
                        "description": "нет/битый/просроченный токен",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создаёт нового пользователя и сразу выдаёт access-токен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Email и пароль",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "невалидное тело / email / пароль",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "email уже занят",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Проверяет, что сервер жив и соединение с БД работает.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":\\\"ok\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "{\\\"status\\\":\\\"db unavailable\\\",\\\"error\\\":\\\"...\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/learning/answer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет level и last_reviewed_at по правилам learning/review. graduated=true при переходе с level ниже 10 на 10 или выше.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "Ответ по карточке",
                "parameters": [
                    {
                        "description": "progress_id и known",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.answerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.answerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "progress не найден",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/learning/batch-start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "На каждый word_id создаётся по две строки progress (оба направления) с level 0. Уже существующие пары пропускаются (идемпотентность).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "Старт пачки из онбординга",
                "parameters": [
                    {
                        "description": "Список word_id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.batchStartRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.batchStartResponse"
                        }
                    },
                    "400": {
                        "description": "пустой список, слишком много id, невалидные id",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/learning/next": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "mode=learning — level меньше 10; mode=review — уровни 10–20 с выборкой 7:3:1 по «плохо/хорошо/отлично». direction задаёт направление карточки (en_ru или ru_en). Если карточек нет — в ответе только progress_id: null.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "Следующая карточка для повторения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "learning или review",
                        "name": "mode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "en_ru или ru_en",
                        "name": "direction",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Для mode=learning: id progress через запятую; клиент передаёт строки, по которым уже ответили «знаю» в этой сессии по этому направлению",
                        "name": "exclude",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.nextResponse"
                        }
                    },
                    "400": {
                        "description": "нет mode или direction, неверные значения",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/learning/next-candidate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Слово из словаря, у которого у пользователя ещё нет записей в progress. Query exclude — id через запятую (корзина и скипы текущей сессии на фронте). Если кандидатов нет — в теле word: null.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "Следующее новое слово (онбординг)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID слов через запятую, исключить из выборки, например: 12,45,78",
                        "name": "exclude",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.nextCandidateResponse"
                        }
                    },
                    "400": {
                        "description": "невалидный id в exclude",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/learning/rate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт две строки progress (en_ru и ru_en) с одним level: bad→10, good→14, perfect→18.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "Оценить рангом в онбординге",
                "parameters": [
                    {
                        "description": "word_id и rank",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.rateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.rateResponse"
                        }
                    },
                    "400": {
                        "description": "невалидное тело, неизвестный rank, невалидный word_id",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "слово не найдено",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/learning/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "Статистика прогресса по ведёркам",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.statsResponse"
                        }
                    }
                }
            }
        },
        "/words": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Форма multipart: текстовые поля + опциональный файл image (JPEG/PNG/WebP, до 5 МБ).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Создать приватное слово",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Слово",
                        "name": "word",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Перевод",
                        "name": "translation",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Пример на английском",
                        "name": "example_en",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Пример на русском",
                        "name": "example_ru",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Картинка",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Word"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/words/check": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Точные совпадения по написанию (омонимы), похожие (pg_trgm) и вхождение подстроки; секции дедуплицированы по id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Проверка слова перед созданием",
                "parameters": [
                    {
                        "description": "Введённое слово",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.wordCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.WordCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/words/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает карточку, если слово общее или создано текущим пользователем.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Слово по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "ID слова",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Word"
                        }
                    },
                    "400": {
                        "description": "невалидный id",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "нет доступа или слово не найдено",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "superSecret123"
                }
            }
        },
        "handler.MeResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "handler.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "superSecret123"
                }
            }
        },
        "handler.WordCheckResponse": {
            "type": "object",
            "properties": {
                "contains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Word"
                    }
                },
                "exact_match": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Word"
                    }
                },
                "similar": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.WordWithSimilarity"
                    }
                }
            }
        },
        "handler.answerRequest": {
            "type": "object",
            "properties": {
                "known": {
                    "type": "boolean",
                    "example": true
                },
                "progress_id": {
                    "type": "integer",
                    "example": 321
                }
            }
        },
        "handler.answerResponse": {
            "type": "object",
            "properties": {
                "graduated": {
                    "type": "boolean",
                    "example": false
                },
                "new_level": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "handler.batchStartRequest": {
            "type": "object",
            "properties": {
                "word_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "handler.batchStartResponse": {
            "type": "object",
            "properties": {
                "created_count": {
                    "type": "integer"
                }
            }
        },
        "handler.bucketStatsResponse": {
            "type": "object",
            "properties": {
                "bad": {
                    "type": "integer"
                },
                "good": {
                    "type": "integer"
                },
                "in_progress": {
                    "type": "integer"
                },
                "new": {
                    "type": "integer"
                },
                "perfect": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.nextCandidateResponse": {
            "type": "object",
            "properties": {
                "word": {
                    "$ref": "#/definitions/model.Word"
                }
            }
        },
        "handler.nextResponse": {
            "type": "object",
            "properties": {
                "direction": {
                    "$ref": "#/definitions/model.Direction"
                },
                "level": {
                    "type": "integer"
                },
                "progress_id": {
                    "type": "integer"
                },
                "word": {
                    "$ref": "#/definitions/model.Word"
                }
            }
        },
        "handler.rateRequest": {
            "type": "object",
            "properties": {
                "rank": {
                    "type": "string",
                    "enum": [
                        "bad",
                        "good",
                        "perfect"
                    ],
                    "example": "bad"
                },
                "word_id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "handler.rateResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                }
            }
        },
        "handler.statsResponse": {
            "type": "object",
            "properties": {
                "en_ru": {
                    "$ref": "#/definitions/handler.bucketStatsResponse"
                },
                "ru_en": {
                    "$ref": "#/definitions/handler.bucketStatsResponse"
                },
                "total": {
                    "$ref": "#/definitions/handler.bucketStatsResponse"
                }
            }
        },
        "handler.wordCheckRequest": {
            "type": "object",
            "properties": {
                "word": {
                    "type": "string",
                    "example": "backyard"
                }
            }
        },
        "model.Direction": {
            "type": "string",
            "enum": [
                "en_ru",
                "ru_en"
            ],
            "x-enum-varnames": [
                "DirectionEnRu",
                "DirectionRuEn"
            ]
        },
        "model.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_superuser": {
                    "type": "boolean"
                }
            }
        },
        "model.Word": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "example_en": {
                    "type": "string"
                },
                "example_ru": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_path": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "repository.WordWithSimilarity": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "example_en": {
                    "type": "string"
                },
                "example_ru": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_path": {
                    "type": "string"
                },
                "similarity": {
                    "type": "number",
                    "format": "float64"
                },
                "translation": {
                    "type": "string"
                },
                "word": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Lexis API",
	Description:      "API сервиса для изучения английских слов.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
